#!/bin/bash
red='\e[1;31m'
green='\e[1;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
echo -e "\e[32mloading...\e[0m"
clear
echo " "
clear



yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\e[33;1m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
# . Liner 
function baris_panjang() {
  echo -e "\e[33;1m ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "\e[92;1m           LUNATIC TUNNELING      ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[1;33m      Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[1;33m             Script Credit \033[0m"
echo -e "\033[1;33m           Lunatic Tunneling  \033[0m"
baris_panjang
exit 1
}

# jalankan loading : sleep 0.8 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}



echo -e "\e[33;1m┌──────────────────────────────────────────┐\033[0m"
echo -e "\e[92;1m   USERNAME       EXP DATE         STATUS           \033[0m"
echo -e "\e[33;1m└──────────────────────────────────────────┘\033[0m"
echo -e "\e[33;1m┌──────────────────────────────────────────┐\033[0m"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "LOCKED${NORMAL}"
else
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "\e[33;1m└──────────────────────────────────────────┘\033[0m"
echo -e "\e[33;1m┌──────────────────────────────────────────┐\033[0m"
echo -e "\e[92;1m   Account number: $JUMLAH   user \e[0m"
echo -e "\e[33;1m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Input Username you want to lock: " username

# // Loading
sleep 0.8 & loading $!

egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
passwd -l $username
clear
Lunatic_Banner
  echo " "
  baris_panjang
  echo -e "${GreenBe} Succesfully ${Xark} "
  echo -e ""
  echo -e "${yellow} Username  : $username ${Xark} "
  echo -e "${yellow} Status    : LOCKED!! ${Xark} "
  echo -e ""
  baris_panjang
Sc_Credit
else
echo "Username not found on your server."
    exit 1
fi